macro(add_example_target NAME SRCS)
  add_executable("${NAME}" "${SRCS}")
  set_target_properties("${NAME}" PROPERTIES CXX_STANDARD 20)
  target_include_directories("${NAME}" PRIVATE "${INLINE_HTML_INCLUDE_DIR}"
                                             include)
  target_link_libraries("${NAME}" PRIVATE "inline_html")
  target_compile_features("${NAME}" PRIVATE cxx_std_20)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_compile_options("${NAME}" PRIVATE "-Wall")
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    target_compile_options("${NAME}" PRIVATE "/W4")
  endif()
endmacro()

macro(add_test_target NAME SRCS)
  add_example_target("${NAME}" "${SRCS}")
  add_test("${NAME}" "${NAME}")
endmacro()
