macro(add_example_target EXAMPLE_NAME SRCS)
  add_executable("${EXAMPLE_NAME}" "${SRCS}")
  set_target_properties("${EXAMPLE_NAME}" PROPERTIES CXX_STANDARD 20)
  target_link_libraries("${EXAMPLE_NAME}" PRIVATE "${PROJECT_NAME}")
  target_compile_features("${EXAMPLE_NAME}" PRIVATE cxx_std_20)

  if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_compile_options("${EXAMPLE_NAME}" PRIVATE "-Wall")
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    target_compile_options("${EXAMPLE_NAME}" PRIVATE "/W4")
  endif()
endmacro()

macro(add_test_target TEST_NAME SRCS)
  add_example_target("${TEST_NAME}" "${SRCS}")
  add_test("${TEST_NAME}" "${TEST_NAME}")
endmacro()
